services:
  postgres:
    image: postgres:18
    container_name: crematory_postgres
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - crematory_network

  redis:
    image: redis:7-alpine
    container_name: crematory_redis
    restart: always
    env_file:
      - ./server/.env
    command:
      [
        "sh",
        "-c",
        "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD",
      ]
    volumes:
      - redisdata:/data
    networks:
      - crematory_network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: crematory_backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "8080:4000"
    depends_on:
      - postgres
      - redis
    networks:
      - crematory_network

volumes:
  pgdata:
  redisdata:

networks:
  crematory_network:
